# Generated by Django 4.2.3 on 2023-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookstoremodel',
            name='book_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
